version: "3.8"
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: >
      bash -c " python scraper.py && python skills.py"

    # Restart on failure
    restart: on-failure
